# Generated by Django 4.2.1 on 2023-09-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fetchbook',
            old_name='isbn13isbn',
            new_name='isbn',
        ),
    ]
