# Generated by Django 4.2.1 on 2023-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_isbn13isbn_fetchbook_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchbook',
            name='fetch_date',
            field=models.DateField(),
        ),
    ]
