# Generated by Django 4.2.1 on 2023-09-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_fetchbook_fetch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fetchbook',
            name='isbn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fetchbook',
            name='isbn13',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fetchbook',
            name='publication_date',
            field=models.CharField(max_length=100),
        ),
    ]
