# Generated by Django 4.2.1 on 2023-09-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_fetchbook_isbn_alter_fetchbook_isbn13_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetchbook',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images'),
        ),
    ]
