# Generated by Django 4.2.1 on 2023-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_fetchbook_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpurchase',
            name='user',
        ),
        migrations.AddField(
            model_name='fetchbook',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
