# Generated by Django 4.2.1 on 2023-09-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_bookpurchase_user_fetchbook_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpurchase',
            name='fetchBook',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.fetchbook'),
        ),
    ]
