# Generated by Django 4.2.1 on 2023-09-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_bookpurchase_fetchbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookpurchase',
            name='amount',
        ),
        migrations.AddField(
            model_name='fetchbook',
            name='amount',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
