# Generated by Django 4.2.1 on 2023-10-01 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_bookpurchase_amount_fetchbook_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetchbook',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='fetchbook',
            name='fetch_date',
        ),
    ]
